# Generated by Django 5.0.6 on 2024-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('rate', models.IntegerField(verbose_name='امتیاز')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('time', models.IntegerField(verbose_name='زمان آماده شدن')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(blank=True, upload_to='foods/', verbose_name='عکس')),
            ],
        ),
    ]
