# Generated by Django 5.0.6 on 2024-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('Lunch', 'ناهار'), ('Dinner', 'شام'), ('Drink', 'نوشیدنی')], default='Lunch', max_length=20, verbose_name='نوع غذا'),
        ),
    ]
